models/product.py
from sqlalchemy import *
from extentions import db
class Product(db.Model):
    __tablename__ = "products"
    id = Column(Integer, primary_key=True)
    name = Column(String, unique=True, nullable=False, index=True)
    description = Column(String, nullable=False, index=True)
    price = Column(Integer, nullable=False, index=True)
    active = Column(Integer, nullable=False, index=True)

blueprints/general.py
from flask import Blueprint, render_template,request
from sqlalchemy.sql.expression import func
from models.product import Product

app = Blueprint("general", __name__)


@app.route('/')
def main():
    search = request.args.get("search" ,None)
    products = Product.query.filter(Product.active == 1)
    if search != None:
        products = products.filter(Product.name.like(f'%{search}%'))

    products=products.order_by(func.random()).all()

    return render_template("main.html", products=products)


@app.route("/product/<int:id>/<name>")
def product(id, name):
    product = Product.query.filter(Product.id == id).filter(Product.name == name).filter(Product.active == 1).first_or_404()


    another_products = Product.query.filter(Product.active==1).filter(Product.name.like(f'%{product.name[0:10]}%')).order_by(func.random()).limit(5).all()


    return render_template('product.html', product=product , another_products=another_products)





@app.route('/about')
def about():  # put application's code here
    return render_template("about.html")

templates/part/header.html
<header class="header">

  <nav>
    <div class="logo">
      <img  class="header-img" src="{{ url_for('static',filename='image/loogoo2.jpg' ) }}" alt="werco.ir">
    </div>
    <input type="checkbox" id="menu-toggle">
    <label for="menu-toggle" class="menu-icon">&#9776;</label>
    <ul class="menu">
                   <li><a href="/">صفحه اصلی</a></li>
                    <li><a href="/about">درباره ما</a></li>
                    <li><a href="/cart">سبد خرید</a></li>
                    <li><a href="/user/dashboard">پنل کاربری</a></li>
                    <li><a href="/admin/login">پنل مدیریت</a></li>
                    <li><a href="/user/login">ثبت نام/ ورود</a></li>
                    <li><a href="/user/logout">خروج</a></li>
    </ul>
  </nav>

</header>
<body>
<div class="header-text">
    <h1 style=> Werco</h1>
    <h2> سازنده سایت های
        اینترنتی فروشگاهی خدماتی و شرکتی </h2>
    <p>وبسایت های کدنویسی شده اماده با اپشن ها و تم های مختلف با پشتیبانی 6 ماهه وشخصی سازی در اختیار شما
        قرار
        گرفته اند شما میتوانید از قالب های ما با قیمت کمتر و سرعت تحویل بیشتر استفاده کنید

        و یا از طریق راه های ارتباطی درپایین صفحه سفارشتون رو ثبت کنید همکاران ما در اولین فرصت با شما تماس
        خواهند گرفت </p>



</div>
 <form class="search" action="/" method="get">

        <input type="search" name="search" placeholder=" جست وجو..."
               value="{{ search if search != None }}">
        <button type="submit" class="search-btn">ارسال
        </button>
    </form>
</body>

templates/part/product.html
<div class="product-box">

    <a style="all:unset;cursor: pointer" ; href="{{ url_for('general.product', id=p.id, name=p.name ) }}">
        <section>
            <img class="main-img" src="{{ url_for('static', filename='cover/' +p.id|string+'.jpg') }}">
            <span class="tag red " style="margin-right:5px ;"><img
                    src="{{ url_for('static',filename="theme-image/support.png") }}">6 ماه پشتیبانی</span>
            <span class="tag blue"><img
                    src="{{ url_for('static',filename="theme-image/vip.png") }}"> ویرایش اختصاصی</span>

            <h3>{{ p.name }}</h3>
            <P>{{ p.description|truncate(100) }}</p>
            <span class="price" style=" float: left;padding-left: 10px;">{{ p.price }}</span>

        </section>
    </a>
    <a class="add-to-cart-btn" href="/add-to-cart?id={{ p.id }}">افزودن به<img
            src="{{ url_for('static',filename="theme-image/cart.png") }}"></a>


</div>