models/cart.py
from sqlalchemy import *
from extentions import db
from sqlalchemy.orm import backref


class Cart(db.Model):
    __tablename__ = "carts"
    id = Column(Integer, primary_key=True)
    status = Column(String, default="pending")
    user_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    user = db.relationship('User', backref=backref('carts', lazy='dynamic'))


    def total_price(self):
        total = 0
        for item in self.cart_items:
            t = item.price * item.quantity
            total += t
        return total


    def get_status_persion(self):
        if self.status == "pending":
            return "در انتظار پرداخت(سبد خرید)"
        elif self.status == "paid":
            return "پرداخت شده"
        elif self.status == "sent":
            return "ارسال شده"
        elif self.status == "rejected":
            return "رد شده"

models/user.py
from sqlalchemy import *
from extentions import db,get_current_time
from flask_login import UserMixin


class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True, nullable=False, index=True)
    email = Column(String,nullable=False, index=True)
    password = Column(String,nullable=False, index=True)
    phone = Column(String(11), nullable=False, index=True)
    address = Column(String, nullable=False, index=True)
    date_created = Column(String(15), default=get_current_time)

blueprints/user.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, json
from flask_login import login_user, login_required, current_user,logout_user
from passlib.hash import sha256_crypt
from extentions import db
from models.cart import Cart
from models.payment import Payment
from models.product import Product
from models.user import User
from models.cart_item import CartItem
import requests

app = Blueprint("user", __name__)


@app.route('/user/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        if current_user.is_authenticated:
            return redirect(url_for('user.dashboard'))
        return render_template('user/login.html')
    else:
        register = request.form.get('register', None)
        username = request.form.get('username', None)
        password = request.form.get('password', None)
        email = request.form.get('email', None)
        phone = request.form.get('phone', None)
        address = request.form.get('address', None)

        if register != None:
            user = User.query.filter(User.username == username).first()
            if user != None:
                flash("نام کاربری دیگری انتخاب کنید.")
                return redirect(url_for("user.login"))

            user = User(username=username, password=sha256_crypt.encrypt(password), email=email, phone=phone,
                        address=address)
            db.session.add(user)
            db.session.commit()
            login_user(user)

            return redirect(url_for('user.dashboard'))
        else:
            user = User.query.filter(User.username == username).first()
            if user == None:
                flash('نام کاربری یا رمزعبور اشتباه است.')
                return redirect(url_for("user.login"))

            if sha256_crypt.verify(password, user.password):
                login_user(user)
                return redirect(url_for('user.dashboard'))
            else:
                flash('رمزعبور اشتباه است.')
                return redirect(url_for("user.login"))


@app.route('/user/login', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('user/login.html')
    else:
        register = request.form.get('register', None)
        username = request.form.get('username')
        password = request.form.get('password')
        email = request.form.get('email')
        phone = request.form.get('phone')
        address = request.form.get('address')

        if register != None:
            user = User(username=username, password=sha256_crypt.encrypt(password), email=email, phone=phone,
                        address=address)
            flash('وارد حساب کاربری شدید.')
            db.session.add(user)
            db.session.commit()
            login_user(user)

            return redirect('/user/dashboard')
        return 'done'


@app.route('/user/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    if request.method == 'GET':
        flash('وارد حساب کاربری شدید.')
        return render_template('user/dashboard.html')
    else:
        username = request.form.get('username', None)
        password = request.form.get('password', None)
        email = request.form.get('email', None)
        phone = request.form.get('phone', None)
        address = request.form.get('address', None)

        if current_user.username != username:
            user = User.query.filter(User.username == username).first()
            if user != None:
                flash("نام کاربری از قبل انتخاب شده است!")
                return redirect(url_for("user.dashboard"))
            else:
                current_user.username = username
        if password != None:
            current_user.password = sha256_crypt.encrypt(password)

        current_user.email = email
        current_user.phone = phone
        current_user.address = address
        db.session.commit()
        flash("تغییرات با موفقیت انجام شد.")

        return redirect(url_for('user.dashboard'))


@app.route('/add-to-cart', methods=['GET'])
@login_required
def add_to_cart():
    id = request.args.get('id')
    product = Product.query.filter(Product.id == id).first_or_404()

    cart = current_user.carts.filter(Cart.status == "pending").first()
    if cart == None:
        cart = Cart()
        current_user.carts.append(cart)
        db.session.add(cart)

    cart_item = cart.cart_items.filter(CartItem.product == product).first()
    if cart_item == None:
        item = CartItem(quantity=1)
        item.price = product.price
        item.cart = cart
        item.product = product
        db.session.add(item)
    else:
        cart_item.quantity += 1
    flash('به سبد خرید اضافه شد')
    db.session.commit()

    return redirect(url_for('user.cart'))





@app.route('/user/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    flash("از حساب کاربری خارج شدید.")
    return redirect("/")

@app.route('/remove-from-cart', methods=['GET'])
@login_required
def remove_from_cart():
    id = request.args.get('id')
    cart_item = CartItem.query.filter(CartItem.id == id).first_or_404()
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
    else:
        db.session.delete(cart_item)
    db.session.commit()

    return redirect(url_for('user.cart'))


@app.route('/cart', methods=['GET'])
@login_required
def cart():
    cart = current_user.carts.filter(Cart.status == "pending").first()
    return render_template('user/cart.html', cart=cart)


@app.route('/payment', methods=['GET'])
@login_required
def payment():
    r = requests.post('https://payment.zarinpal.com/pg/v4/payment/request.json',
                      data={
                            'merchant_id': '73a4c8d3-8e5a-4909-827e-fd3e0b1574c4',
                            'amount': '1000',
                            'callback_url': 'localhost:5000/verify',
                      })
    print(r.text)
    return "okk"

@app.route('/user/dashboard/order/<id>', methods=['GET'])
@login_required
def order(id):
    cart = current_user.carts.filter(Cart.id == id).first_or_404()
    return render_template('user/order.html', cart=cart)

templates/user/cart.html
{% extends 'base.html' %}

{% block header %}
    <title>سبد خرید </title>
{% endblock %}

{% block body %}
    <section class="cart-body">
       <header class="header">

  <nav>
    <div class="logo">
      <img  class="header-img" src="{{ url_for('static',filename='image/loogoo2.jpg' ) }}" alt="werco.ir">
    </div>
    <input type="checkbox" id="menu-toggle">
    <label for="menu-toggle" class="menu-icon">&#9776;</label>
    <ul class="menu">
                   <li><a href="/">صفحه اصلی</a></li>
                    <li><a href="/about">درباره ما</a></li>
                    <li><a href="/cart">سبد خرید</a></li>
                    <li><a href="/user/dashboard">پنل کاربری</a></li>
                    <li><a href="/admin/login">پنل مدیریت</a></li>
                    <li><a href="/user/login">ثبت نام/ ورود</a></li>
    </ul>
  </nav>

</header>
        <section class="simple-box">
            <h1>سبد خرید</h1>
            {% if cart != None and cart.cart_items|list|length > 0 %}
                <table class="cart-table">
                    <tr>
                        <th>کد محصول</th>
                        <th>نام محصول</th>
                        <th>تعداد</th>
                        <th>قیمت</th>
                    </tr>
                    {% for cart_item in cart.cart_items %}
                        <tr>
                            <td>{{ cart_item.product.id }}</td>
                            <td>{{ cart_item.product.name }}</td>
                            <td><a class="cartitem-decrease"
                                   href="/remove-from-cart?id={{ cart_item.id }}">-</a>{{ cart_item.quantity }}<a
                                    class="cartitem-increase" href="/add-to-cart?id={{ cart_item.product.id }}">+</a>
                            </td>
                            <td class="price">{{ cart_item.product.price }}</td>
                        </tr>

                    {% endfor %}
                    <tr>
                        <td>قیمت کل:</td>
                        <td colspan="3" style="text-align: left"><span
                                class="price">{{ cart.total_price() }}تومان</span></td>
                    </tr>
                </table>
                <div class="cart-price-box">

                    <a class="add-to-cart-btn2" href="/payment">پرداخت</a>
                </div>



            {% else %}
                سبد خرید خالی است
            {% endif %}


        </section>


    </section>

{% endblock %}

templates/user/dashboard.html
{% extends 'base.html' %}

{% block header %}
    <title>پنل کاربری</title>
{% endblock %}

{% block body %}
    <section class="user-dashboard-body">
        <header class="header">

            <nav>
                <div class="logo">
                    <img class="header-img" src="{{ url_for('static',filename='image/loogoo2.jpg' ) }}" alt="werco.ir">
                </div>
                <input type="checkbox" id="menu-toggle">
                <label for="menu-toggle" class="menu-icon">&#9776;</label>
                <ul class="menu">
                    <li><a href="/">صفحه اصلی</a></li>
                    <li><a href="/about">درباره ما</a></li>
                    <li><a href="/cart">سبد خرید</a></li>
                    <li><a href="/user/dashboard">پنل کاربری</a></li>
                    <li><a href="/admin/login">پنل مدیریت</a></li>
                    <li><a href="/user/login">ثبت نام/ ورود</a></li>
                </ul>
            </nav>

        </header>
        <section class="simple-box-user-dashboard">

            <h1>سفارشات</h1>
            {% if current_user.carts|selectattr('status','!=','pending')|list|length > 0 %}
                <table class="cart">
                    <tr>
                        <th>شماره سفارش</th>
                        <th>وضعیت</th>
                        <th>مشاهده وضعیت</th>
                        {% for cart in current_user.carts|selectattr('status','!=','pending') %}
                            <tr>
                                <td>{{ cart.id }}</td>
                                <td>{{ cart.get_status_persion() }}</td>
                                <td><a href="{{ url_for('user.order',id=cart.id) }}">جزئیات</a></td>
                            </tr>
                            <br>
                        {% endfor %}
                </table>
            {% else %}
                <i style="display: block; text-align: center">سفارشی وجود ندارد.</i>
            {% endif %}

        </section>
        <section class="simple-box-edit">
            <h1> ویرایش اطلاعات </h1>
            <form action="#" method="POST">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="text" name="username" value="{{ current_user.username }}" placeholder="نام کاربری">
                <input type="password" name="password" placeholder="رمز عبور جدید">
                <input type="email" name="email" value="{{ current_user.email }}" placeholder="ایمیل">
                <input type="number" name="phone" value="{{ current_user.phone }}" placeholder="شماره موبایل">
                <textarea name="address" type="text" placeholder="ادرس پستی">{{ current_user.address }} </textarea>
                <input type="submit" value=" ثبت تغییرات">
            </form>
        </section>

    </section>
{% endblock %}

templates/user/login.html
{% extends 'base.html' %}

{% block header %}
    <title>ورود/ثبت نام </title>
{% endblock %}

{% block body %}
    <section class="login-body">
        <header class="header">

  <nav>
    <div class="logo">
      <img  class="header-img" src="{{ url_for('static',filename='image/loogoo2.jpg' ) }}" alt="werco.ir">
    </div>
    <input type="checkbox" id="menu-toggle">
    <label for="menu-toggle" class="menu-icon">&#9776;</label>
    <ul class="menu">
                   <li><a href="/">صفحه اصلی</a></li>
                    <li><a href="/about">درباره ما</a></li>
                  
    </ul>
  </nav>

</header>
        <section class="simple-box">

            <div id="login-box">
                <h1>ورود</h1>
                <form action="#" method="POST">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <input type="text" name="username" placeholder="نام کاربری">
                    <input type="password" name="password" placeholder="رمز عبور">

                    <input type="submit" value="ورود">
                </form>
                <span style="cursor: pointer"
                      onclick="javascript:show_register()">قبلا ثبت نام   نکرده اید؟ثبت نام</span>
            </div>

            <div id="register-box">
                <h1>ثبت نام</h1>
                <form action="#" method="POST">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <input type="hidden" name="register" value="1">
                    <input type="text" name="username" placeholder="نام کاربری">
                    <input type="password" name="password" placeholder="رمز عبور">
                    <input type="email" name="email" placeholder="ایمیل">
                    <input type="number" name="phone" placeholder="شماره موبایل">
                    <textarea name="address" type="text" placeholder="ادرس پستی"></textarea>
                    <input type="submit" value="ثبت">
                </form>
                <span style="cursor: pointer" onclick="javascript:show_login()">قبلا ثبت نام   کرده اید؟ورود</span>
            </div>


        </section>

        <script>
            const register_box = document.getElementById('register-box')
            const login_box = document.getElementById('login-box')

            const show_register = () => {
                register_box.style.display = "block"
                login_box.style.display = "none"
            }

            const show_login = () => {
                register_box.style.display = "none"
                login_box.style.display = "block"
            }
        </script>


    </section>
{% endblock %}

templates/user/order.html
{% extends 'base.html' %}

{% block header %}
    <title>سفارش شماره{{ cart.id }} </title>
{% endblock %}

{% block body %}
    <section class="order-body">
<header class="header">

  <nav>
    <div class="logo">
      <img  class="header-img" src="{{ url_for('static',filename='image/loogoo2.jpg' ) }}" alt="werco.ir">
    </div>
    <input type="checkbox" id="menu-toggle">
    <label for="menu-toggle" class="menu-icon">&#9776;</label>
    <ul class="menu">
                   <li><a href="/">صفحه اصلی</a></li>
                    <li><a href="/about">درباره ما</a></li>
                    <li><a href="/cart">سبد خرید</a></li>
                    <li><a href="/user/dashboard">پنل کاربری</a></li>
                    <li><a href="/admin/login">پنل مدیریت</a></li>
                    <li><a href="/user/login">ثبت نام/ ورود</a></li>
    </ul>
  </nav>

</header>


        <section class="simple-box-order">

            <h1>سفارش شماره{{ cart.id }} : {{ cart.get_status_persion() }}</h1>
            <table class="cart-order">
                <tr>
                    <th>شماره محصول</th>
                    <th>نام محصول</th>
                    <th>تعداد</th>
                    <th>قیمت</th>
                </tr>
                {% for item in cart.cart_items %}
                    <tr>
                        <td>{{ item.product.id }}</td>
                        <td>{{ item.product.name }}</td>
                        <td>{{ item.quantity }}</td>
                        <td class="price">{{ item.product.price }}</td>


                    </tr>
                {% endfor %}
                <tr>
                    <td>قیمت کل:</td>
                    <td colspan="3" style="text-align: left" class="price">{{ cart.total_price() }}</td>
                </tr>
            </table>

            <table style="margin-top: 30px">
                <tr>
                    <th>وضعیت</th>
                    <th>مبلغ</th>
                    <th>شماره پیگیری</th>
                    <th>شماره تراکنش</th>
                    <th>شماره کارت</th>

                </tr>
                {% for pay in cart.payments %}
                    <tr>
                        <td>{{ pay.get_status_persion() }}</td>
                        <td class="price">{{ pay.price }}</td>
                         <td>{{ pay.refid }}</td>
                        <td>{{ pay.transaction_id }}</td>
                        <td>{{ pay.cart_pen }}</td>
                    </tr>
                {% endfor %}
            </table>
        </section>
    </section>
    </section>
{% endblock %}